# File: .github/workflows/iplcdn_repo-sync.yml
name: sync-iplcdn-scripts
on:
  schedule:
    - cron: 0 7 * * fri
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-iplcdn-scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT || github.event.client_payload.PAT }} 
      #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
      #https://github.com/iplcdn/auto_repo-sync/blob/master/reposync.md
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync iplcdn-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/t00t00-crypto/wyy-action.git"
          source_branch: "master"
          destination_branch: "master"
          github_token: ${{ secrets.PAT || github.event.client_payload.PAT }}
